dist: focal
os: linux
env:
  global:
    - VOLTA_HOME=$HOME/.volta
    - PATH=$VOLTA_HOME:$PATH
before_install:
  - curl https://get.volta.sh | bash
  - source ~/.bashrc
  # - volta setup --verbose
  - volta install node@15.5.0
  - volta install pnpm@5.14.1
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm --recursive install
script:
  - pnpm --recursive run test
after_success:
  - pnpm --recursive run coverage
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
